name: CI
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to aliyun Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME}}
          password: ${{ secrets.ALIYUN_TOKEN}}
      -
        name: sync github description to dockerhub
        uses: meeDamian/sync-readme@v1.0.6
        with:
          pass: ${{ secrets.DOCKERHUB_TOKEN }}
          description: true
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            metajs/tiddlywiki:latest
            metajs/tiddlywiki:${{ steps.date.outputs.date }}
            registry.cn-hangzhou.aliyuncs.com/metajs/tiddlywiki:latest
            registry.cn-hangzhou.aliyuncs.com/metajs/tiddlywiki:${{ steps.date.outputs.date }}
